### ISSUE TITLE
Could not use require in node?

### ISSUE THREAD

**Issue by m-ar13f** [blackflux/object-scan#1773]
I have tried to give a shot for this library, unfortunately it doesnt support es5 module export. I ended up using jsonata that looks more mature and support es5. Thanks for your hard work to create this library.

**Comment by simlu** [comment]
Thank you for your feedback! Not supporting cjs (or require as you call it) is intentional. This library is not built for old code bases that still use the now outdated require syntax. I wouldn't call object-scan less mature because of it, rather I'd call your code base in need of update =)

I'm glad you found what you are looking for in jsonata. While it also queries data, it has a different scope and tradeoffs (which might not matter to you). I'll try and add it as a library to compare it to. Here is the ticket: https://github.com/blackflux/object-scan/issues/1775

Regarding require: We might support it again as a transitional step. Here is a good read on the subject:

https://antfu.me/posts/publish-esm-and-cjs

I'm treating this as a feature request for now. Please subscribe to [this ticket](https://github.com/blackflux/object-scan/issues/1774) to follow progress. I am currently working on typescript support, so this might fit in with that. 

I'm closing this ticket, but make sure you follow the relevant tickets I created and also feel free to reply here!

**Comment by m-ar13f** [comment]
Thanks for the explanation bro. I'm just confuse that people still using Commonjs in their codebase. 
Like other developer that new in technology stack, i did search library that suit my project, and a lot of them still using commonjs in their example and documentation. I'm coming from python, so this node module system really confuse me. It's my lack of knowledge, once again thank you for the explanation.

**Comment by simlu** [comment]
@m-ar13f Yeah, it's a bit of a mess right now. Maybe compare it to python 2.7 and how long that stuck around. I hope the migration from cjs to esm will be a bit faster than that =)
